### ISSUE TITLE
[ENCHANTMENT] Use albert

### ISSUE THREAD

**Issue by deltaxflux** [rad4day/dotfiles#2]
### Use [Albert](https://github.com/albertlauncher/albert)
Albert is a unified and efficient access to your machine. Technically it is a keyboard launcher written in C++/Qt. The plugin based architecture makes it extremely flexible and powerful....

### Why Albert ?

* flexiable
* snappy 
* ton of modules

### Screenshots
![alt](https://camo.githubusercontent.com/be5cf59b0f7f10ea3b75a81fbc1ef981894a69f7/68747470733a2f2f692e696d6775722e636f6d2f39596337756e702e6a7067)

![alt](https://camo.githubusercontent.com/0d47fbc5b2eaabb4444db79a5508ed8439100f4d/68747470733a2f2f692e696d6775722e636f6d2f42614d6c5769742e6a7067)

![alt](https://camo.githubusercontent.com/e04752d4f15b2c482d95210620cab876bf88bbc5/68747470733a2f2f692e696d6775722e636f6d2f4f436d415947502e6a7067)

![alt](https://camo.githubusercontent.com/55657c529447b41e1fd84ef6e0d461377a719812/68747470733a2f2f692e696d6775722e636f6d2f4c7569416d7a552e6a7067)

Regards,
deltax

**Comment by rad4day** [comment]
Well kinda forgot about this "ISSUE". So it seems like it was not that important after all :P

**Comment by deltaxflux** [comment]
troll
